spring:
  application:
    name: boot-dubbo-provider

server:
  port: 8080

dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: -1