
spring:
  application:
    name: boot-dubbo-rest-consumer


server:
  port: 8081


dubbo:
  application:
    name: dubbo-rest-consumer
  registry:
    address: zookeeper://localhost:2181
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 8889